boss update horse
boss update HashLoad/jhonson
boss update HashLoad/horse-logger
boss update HashLoad/horse-cors
boss update HashLoad/handle-exception
boss update bittencourtthulio/Horse-ETag
boss update viniciussanchez/dataset-serialize
boss update viniciussanchez/RESTRequest4Delphi
boss install HaHashLoad/horse-basic-auth
